version: '3.9'

services:
  social-media-grpc-api:
    build:
      context: .
      dockerfile: Dockerfile.grpc
    container_name: social-media-grpc-api
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres:5432/social_media
      - USE_DB_SEED=True
      - PORT=5000
    ports:
      - "5001:5000"

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=social_media
volumes:
  postgres-data:
