# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import social_media_pb2 as social__media__pb2


class SocialMediaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc_.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/social_media.SocialMedia/GetUser',
                request_serializer=social__media__pb2.GetUserRequest.SerializeToString,
                response_deserializer=social__media__pb2.GetUserResponse.FromString,
                )
        self.GetPost = channel.unary_unary(
                '/social_media.SocialMedia/GetPost',
                request_serializer=social__media__pb2.GetPostRequest.SerializeToString,
                response_deserializer=social__media__pb2.GetPostResponse.FromString,
                )
        self.GetUserSummaries = channel.unary_unary(
                '/social_media.SocialMedia/GetUserSummaries',
                request_serializer=social__media__pb2.GetUserSummariesRequest.SerializeToString,
                response_deserializer=social__media__pb2.GetUserSummariesResponse.FromString,
                )


class SocialMediaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserSummaries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SocialMediaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=social__media__pb2.GetUserRequest.FromString,
                    response_serializer=social__media__pb2.GetUserResponse.SerializeToString,
            ),
            'GetPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPost,
                    request_deserializer=social__media__pb2.GetPostRequest.FromString,
                    response_serializer=social__media__pb2.GetPostResponse.SerializeToString,
            ),
            'GetUserSummaries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserSummaries,
                    request_deserializer=social__media__pb2.GetUserSummariesRequest.FromString,
                    response_serializer=social__media__pb2.GetUserSummariesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'social_media.SocialMedia', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SocialMedia(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/social_media.SocialMedia/GetUser',
                                              social__media__pb2.GetUserRequest.SerializeToString,
                                              social__media__pb2.GetUserResponse.FromString,
                                              options, channel_credentials,
                                              insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/social_media.SocialMedia/GetPost',
                                              social__media__pb2.GetPostRequest.SerializeToString,
                                              social__media__pb2.GetPostResponse.FromString,
                                              options, channel_credentials,
                                              insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserSummaries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/social_media.SocialMedia/GetUserSummaries',
                                              social__media__pb2.GetUserSummariesRequest.SerializeToString,
                                              social__media__pb2.GetUserSummariesResponse.FromString,
                                              options, channel_credentials,
                                              insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
